### ISSUE TITLE
Add optional ath claim to generated DPoP proof in dgt-id-kit

### ISSUE THREAD

**Issue by JasperVandenberghen** [digita-ai/dgt-id-broker#337] opened 2022-03-01 11:27 UTC
```
When the DPoP proof is used in conjunction with the presentation of
an access token, see Section 7, the DPoP proof MUST also contain the
following claim:

*  ath: hash of the access token (REQUIRED).  The value MUST be the
    result of a base64url encoding (with no padding) the SHA-256 hash
    of the ASCII encoding of the associated access token's value.
```

 [source](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop#section-4.2)

Right now we do not support this.  We should add this to be spec compliant.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=853328569) by [Unito](https://www.unito.io)

**Comment by tomhgmns** [comment] 2022-08-02 15:05
Duplicate of #431

**Closed by tomhgmns** 2022-08-02 15:05 UTC
Labels: package:id-kit, compliance
